import html
import smtplib
import socket
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import (
    EMAIL_ALERT_LEVELS,
    EMAIL_ENABLED,
    RECEIVER_EMAIL,
    SENDER_EMAIL,
    SENDER_PASSWORD,
    SMTP_PORT,
    SMTP_SERVER,
)
from database import insert_email_history, mark_alert_email_sent
from utils import now_string


def _value(mapping, key, default=""):
    try:
        return mapping[key] or default
    except Exception:
        return default


def _build_html_email(alert, recommendation):
    severity = html.escape(_value(alert, "severity", "MEDIUM"))
    threat = html.escape(_value(alert, "threat", "SIEM Test Alert"))
    timestamp = html.escape(_value(alert, "last_seen") or _value(alert, "timestamp", now_string()))
    username = html.escape(_value(alert, "username", "SYSTEM"))
    source = html.escape(_value(alert, "source", "SIEM Dashboard"))
    hostname = html.escape(_value(alert, "hostname") or _value(alert, "computer") or "Unknown")
    device_name = html.escape(_value(alert, "computer") or _value(alert, "hostname") or "Unknown")
    ip_address = html.escape(_value(alert, "ip_address", "Unknown"))
    event_type = html.escape(_value(alert, "event_type") or str(_value(alert, "event_id", "N/A")))
    description = html.escape(recommendation.get("description", _value(alert, "message", "A SIEM alert was generated.")))
    actions = recommendation.get("recommended_actions") or recommendation.get("commands") or [
        recommendation.get("immediate_action", "Review the alert context."),
        recommendation.get("recommended_fix", "Investigate and remediate if suspicious."),
    ]
    actions_html = "".join(f"<li>{html.escape(str(action))}</li>" for action in actions if action)
    mitre = html.escape(recommendation.get("mitre", _value(alert, "mitre", "N/A")))

    return f"""
    <!doctype html>
    <html>
      <body style="margin:0;background:#f4f7fb;font-family:Segoe UI,Arial,sans-serif;color:#172033;">
        <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f7fb;padding:24px;">
          <tr>
            <td align="center">
              <table width="720" cellpadding="0" cellspacing="0" style="max-width:720px;background:#ffffff;border:1px solid #dbe4ef;border-radius:10px;overflow:hidden;">
                <tr>
                  <td style="background:#111827;color:#ffffff;padding:22px 26px;">
                    <h1 style="margin:0;font-size:24px;">SIEM Security Alert</h1>
                    <p style="margin:8px 0 0;color:#cbd5e1;">Generated by your Flask SIEM monitoring dashboard</p>
                  </td>
                </tr>
                <tr>
                  <td style="padding:24px 26px;">
                    <p style="margin:0 0 18px;"><strong>Severity:</strong> <span style="color:#b91c1c;font-weight:700;">{severity}</span></p>
                    <table width="100%" cellpadding="8" cellspacing="0" style="border-collapse:collapse;">
                      <tr><td><strong>Hostname</strong></td><td>{hostname}</td></tr>
                      <tr><td><strong>Device Name</strong></td><td>{device_name}</td></tr>
                      <tr><td><strong>IP Address</strong></td><td>{ip_address}</td></tr>
                      <tr><td><strong>Threat Name</strong></td><td>{threat}</td></tr>
                      <tr><td><strong>Timestamp</strong></td><td>{timestamp}</td></tr>
                      <tr><td><strong>Username</strong></td><td>{username}</td></tr>
                      <tr><td><strong>Source</strong></td><td>{source}</td></tr>
                      <tr><td><strong>Event Type</strong></td><td>{event_type}</td></tr>
                      <tr><td><strong>MITRE ATT&CK Technique</strong></td><td>{mitre}</td></tr>
                    </table>
                    <h2 style="font-size:18px;margin:24px 0 8px;">Description</h2>
                    <p style="line-height:1.5;">{description}</p>
                    <h2 style="font-size:18px;margin:24px 0 8px;">Recommended Actions</h2>
                    <ul style="line-height:1.6;">{actions_html}</ul>
                  </td>
                </tr>
                <tr>
                  <td style="background:#f8fafc;color:#64748b;padding:16px 26px;font-size:13px;">
                    Generated automatically by SIEM Dashboard
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </body>
    </html>
    """


def _send_message(subject, html_body):
    if not EMAIL_ENABLED:
        print("[EMAIL] Email sending is disabled in config.py.")
        return False, "Email disabled"

    if not all([SENDER_EMAIL, SENDER_PASSWORD, RECEIVER_EMAIL]):
        print("[EMAIL] Missing SENDER_EMAIL, SENDER_PASSWORD, or RECEIVER_EMAIL in config.py/environment.")
        return False, "Missing email configuration"

    message = MIMEMultipart("alternative")
    message["From"] = SENDER_EMAIL
    message["To"] = RECEIVER_EMAIL
    message["Subject"] = subject
    message.attach(MIMEText(html_body, "html"))

    try:
        print(f"[EMAIL] Connecting to {SMTP_SERVER}:{SMTP_PORT} with TLS...")
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT, timeout=20) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            print(f"[EMAIL] Authenticating as {SENDER_EMAIL}...")
            server.login(SENDER_EMAIL, SENDER_PASSWORD)
            server.send_message(message)
        print(f"[EMAIL] Email sent successfully to {RECEIVER_EMAIL}.")
        return True, "Email sent successfully"
    except smtplib.SMTPAuthenticationError:
        print("[EMAIL] Authentication failed. Check Gmail address and app password.")
        return False, "Authentication failed: wrong Gmail address or app password"
    except smtplib.SMTPConnectError as exc:
        print(f"[EMAIL] SMTP connection failed: {exc}")
        return False, f"SMTP connection failed: {exc}"
    except (socket.timeout, TimeoutError) as exc:
        print(f"[EMAIL] SMTP timeout: {exc}")
        return False, f"SMTP timeout: {exc}"
    except (smtplib.SMTPException, OSError, socket.gaierror) as exc:
        print(f"[EMAIL] Network/SMTP error: {exc}")
        return False, f"Network/SMTP error: {exc}"
    except Exception as exc:
        print(f"[EMAIL] Unexpected email error: {exc}")
        return False, f"Unexpected email error: {exc}"


def send_email_alert(alert, recommendation=None):
    recommendation = recommendation or {}
    severity = _value(alert, "severity", "INFO")
    threat = _value(alert, "threat", "SIEM Alert")
    alert_id = _value(alert, "id", None)
    subject = f"SIEM {severity} Alert: {threat}"

    if severity not in EMAIL_ALERT_LEVELS:
        print(f"[EMAIL] Skipped {severity} alert. Only MEDIUM, HIGH, and CRITICAL alerts are emailed.")
        return False

    if _value(alert, "email_sent", 0):
        print(f"[EMAIL] Duplicate prevented. Alert {alert_id} was already emailed.")
        return False

    html_body = _build_html_email(alert, recommendation)
    sent, detail = _send_message(subject, html_body)

    if sent and alert_id:
        mark_alert_email_sent(alert_id)

    insert_email_history(
        RECEIVER_EMAIL,
        severity,
        subject,
        "SENT" if sent else "FAILED",
        threat=threat,
        alert_id=alert_id,
        error="" if sent else detail,
    )
    return sent


def send_test_email():
    alert = {
        "id": None,
        "severity": "MEDIUM",
        "threat": "Test Email Alert",
        "timestamp": now_string(),
        "last_seen": now_string(),
        "username": "SIEM-Test",
        "hostname": "TEST-HOST",
        "computer": "TEST-HOST",
        "ip_address": "127.0.0.1",
        "source": "Dashboard",
        "event_type": "TEST_EMAIL",
        "message": "This is a test email from the SIEM Dashboard.",
        "mitre": "N/A",
        "email_sent": 0,
    }
    recommendation = {
        "description": "This test confirms Gmail SMTP, TLS, credentials, and database email history logging.",
        "recommended_actions": [
            "Confirm that this message reached the configured receiver inbox.",
            "Check spam or Gmail security notifications if delivery fails.",
            "Use a Gmail app password, not the normal Gmail password.",
        ],
        "mitre": "N/A",
    }
    subject = "SIEM Test Email Alert"
    sent, detail = _send_message(subject, _build_html_email(alert, recommendation))
    insert_email_history(
        RECEIVER_EMAIL,
        "MEDIUM",
        subject,
        "SENT" if sent else "FAILED",
        threat="Test Email Alert",
        error="" if sent else detail,
    )
    return sent, detail
